class CounterModel:
    """
    Maintains people entry, exit, and current-occupancy counts.

    The model consumes ENTER / EXIT events generated by DirectionModel.
    It does not know anything about cameras, tracking, or the UI.
    """

    ENTER = "ENTER"
    EXIT = "EXIT"

    def __init__(self, initial_count=0):
        if not isinstance(initial_count, int):
            raise TypeError("initial_count must be an integer.")

        if initial_count < 0:
            raise ValueError("initial_count cannot be negative.")

        self._entered = 0
        self._exited = 0
        self._current = initial_count

    @property
    def entered(self):
        return self._entered

    @property
    def exited(self):
        return self._exited

    @property
    def current(self):
        return self._current

    def process_event(self, direction):
        """
        Process one ENTER or EXIT event.

        Returns:
            The updated current people count.

        An EXIT event is ignored when nobody is currently inside, preventing
        the current count from becoming negative.
        """
        direction = str(direction).upper()

        if direction == self.ENTER:
            self._entered += 1
            self._current += 1
            return self._current

        if direction == self.EXIT:
            if self._current <= 0:
                return self._current

            self._exited += 1
            self._current -= 1
            return self._current

        raise ValueError(
            f"Unsupported direction: {direction}. "
            f"Expected '{self.ENTER}' or '{self.EXIT}'."
        )

    def process_events(self, events):
        """
        Process multiple direction events.

        Each event may be either:
            - "ENTER" / "EXIT"
            - a dictionary containing a "direction" key

        Returns:
            A dictionary containing the updated counters.
        """
        if events is None:
            return self.get_counts()

        for event in events:
            if isinstance(event, dict):
                direction = event.get("direction")
            else:
                direction = event

            if direction is None:
                continue

            self.process_event(direction)

        return self.get_counts()

    def reset(self, initial_count=0):
        """Reset all counters."""
        if not isinstance(initial_count, int):
            raise TypeError("initial_count must be an integer.")

        if initial_count < 0:
            raise ValueError("initial_count cannot be negative.")

        self._entered = 0
        self._exited = 0
        self._current = initial_count

    def get_counts(self):
        """Return all current counter values."""
        return {
            "entered": self._entered,
            "exited": self._exited,
            "current": self._current,
        }
